// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class types.

use super::*;
use baml::{
    __internal::serde::{Deserialize, Serialize},
    BamlDecode, BamlEncode,
};

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct AggregatedResearchOutput {
    pub title: String,
    pub citation: String,
    pub topics: Vec<String>,
    pub summary: String,
    pub key_ideas: Vec<String>,
    pub implementation_notes: Vec<String>,
    pub critique: String,
    pub evidence_span_ids: Vec<String>,
}

impl ::std::convert::AsRef<AggregatedResearchOutput> for AggregatedResearchOutput {
    fn as_ref(&self) -> &AggregatedResearchOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ClaimOutput {
    pub local_id: String,
    pub text: String,
    pub kind: ClaimKind,
    pub confidence_percent: i64,
    pub evidence_span_ids: Vec<String>,
}

impl ::std::convert::AsRef<ClaimOutput> for ClaimOutput {
    fn as_ref(&self) -> &ClaimOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct DocumentClassification {
    pub title: String,
    pub authors: Vec<String>,
    pub source_type: DocumentSourceType,
    pub language_code: String,
    pub topics: Vec<String>,
}

impl ::std::convert::AsRef<DocumentClassification> for DocumentClassification {
    fn as_ref(&self) -> &DocumentClassification {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct DocumentIntelligenceOutput {
    pub summary: String,
    pub key_points: Vec<String>,
    pub summary_span_ids: Vec<String>,
    pub claims: Vec<ClaimOutput>,
    pub entities: Vec<EntityOutput>,
    pub relations: Vec<SemanticRelationOutput>,
}

impl ::std::convert::AsRef<DocumentIntelligenceOutput> for DocumentIntelligenceOutput {
    fn as_ref(&self) -> &DocumentIntelligenceOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct EntityOutput {
    pub local_id: String,
    pub name: String,
    pub aliases: Vec<String>,
    pub kind: EntityKind,
    pub description: String,
    pub evidence_span_ids: Vec<String>,
}

impl ::std::convert::AsRef<EntityOutput> for EntityOutput {
    fn as_ref(&self) -> &EntityOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct EvidenceReferenceOutput {
    pub quote: String,
    pub location: String,
}

impl ::std::convert::AsRef<EvidenceReferenceOutput> for EvidenceReferenceOutput {
    fn as_ref(&self) -> &EvidenceReferenceOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct IntelligenceChunkOutput {
    pub summary: String,
    pub key_points: Vec<String>,
    pub summary_span_ids: Vec<String>,
    pub claims: Vec<ClaimOutput>,
    pub entities: Vec<EntityOutput>,
    pub relations: Vec<SemanticRelationOutput>,
}

impl ::std::convert::AsRef<IntelligenceChunkOutput> for IntelligenceChunkOutput {
    fn as_ref(&self) -> &IntelligenceChunkOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ResearchChunkOutput {
    pub summary: String,
    pub key_ideas: Vec<String>,
    pub implementation_notes: Vec<String>,
    pub critique_points: Vec<String>,
    pub evidence_span_ids: Vec<String>,
}

impl ::std::convert::AsRef<ResearchChunkOutput> for ResearchChunkOutput {
    fn as_ref(&self) -> &ResearchChunkOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ResearchDraftOutput {
    pub title: String,
    pub citation: String,
    pub topics: Vec<String>,
    pub summary: String,
    pub key_ideas: Vec<String>,
    pub implementation_notes: Vec<String>,
    pub critique: String,
    pub evidence: Vec<EvidenceReferenceOutput>,
}

impl ::std::convert::AsRef<ResearchDraftOutput> for ResearchDraftOutput {
    fn as_ref(&self) -> &ResearchDraftOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct SemanticRelationOutput {
    pub source_local_id: String,
    pub target_local_id: String,
    pub relation_type: SemanticRelationType,
    pub confidence_percent: i64,
    pub evidence_span_ids: Vec<String>,
}

impl ::std::convert::AsRef<SemanticRelationOutput> for SemanticRelationOutput {
    fn as_ref(&self) -> &SemanticRelationOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct SourceSpanInput {
    pub id: String,
    pub text: String,
    pub location: String,
}

impl ::std::convert::AsRef<SourceSpanInput> for SourceSpanInput {
    fn as_ref(&self) -> &SourceSpanInput {
        self
    }
}
