// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class types.

use super::*;
use baml::{
    __internal::serde::{Deserialize, Serialize},
    BamlDecode, BamlEncode,
};

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct DocumentClassification {
    pub title: String,
    pub authors: Vec<String>,
    pub source_type: String,
    pub language: String,
    pub topics: Vec<String>,
}

impl ::std::convert::AsRef<DocumentClassification> for DocumentClassification {
    fn as_ref(&self) -> &DocumentClassification {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct EvidenceReferenceOutput {
    pub quote: String,
    pub location: String,
}

impl ::std::convert::AsRef<EvidenceReferenceOutput> for EvidenceReferenceOutput {
    fn as_ref(&self) -> &EvidenceReferenceOutput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ResearchDraftOutput {
    pub title: String,
    pub citation: String,
    pub topics: Vec<String>,
    pub summary: String,
    pub key_ideas: Vec<String>,
    pub implementation_notes: Vec<String>,
    pub critique: String,
    pub evidence: Vec<EvidenceReferenceOutput>,
}

impl ::std::convert::AsRef<ResearchDraftOutput> for ResearchDraftOutput {
    fn as_ref(&self) -> &ResearchDraftOutput {
        self
    }
}
