// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated BAML types.

mod classes;
mod enums;
mod type_aliases;
mod unions;

pub use classes::*;
pub use enums::*;
pub use type_aliases::*;
pub use unions::*;

// Re-export types from baml runtime
use baml::__internal::serde;
pub use baml::{Audio, Image, Pdf, Video};
pub use baml::{Checked, StreamState};

/// All known types in this BAML project.
/// Serves as the compile-time type registry for BamlValue.
#[derive(Debug, Clone, serde::Serialize)]
#[serde(crate = "::baml::__internal::serde", untagged)]
pub enum Types {
    AggregatedResearchOutput(AggregatedResearchOutput),

    DocumentClassification(DocumentClassification),

    EvidenceReferenceOutput(EvidenceReferenceOutput),

    ResearchChunkOutput(ResearchChunkOutput),

    ResearchDraftOutput(ResearchDraftOutput),

    SourceSpanInput(SourceSpanInput),
}

impl ::baml::KnownTypes for Types {
    fn as_any(&self) -> &dyn ::std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {
            Self::AggregatedResearchOutput(_) => "AggregatedResearchOutput",

            Self::DocumentClassification(_) => "DocumentClassification",

            Self::EvidenceReferenceOutput(_) => "EvidenceReferenceOutput",

            Self::ResearchChunkOutput(_) => "ResearchChunkOutput",

            Self::ResearchDraftOutput(_) => "ResearchDraftOutput",

            Self::SourceSpanInput(_) => "SourceSpanInput",
        }
    }
}

impl<'de> serde::Deserialize<'de> for Types {
    fn deserialize<D: serde::Deserializer<'de>>(
        _deserializer: D,
    ) -> ::std::result::Result<Self, D::Error> {
        ::std::result::Result::Err(serde::de::Error::custom(
            "Types is not deserializable, as we cannot disambiguate the type.",
        ))
    }
}
