// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class builder wrappers for type-safe field access.

/// Wrapper for the `AggregatedResearchOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct AggregatedResearchOutputClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl AggregatedResearchOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type().expect(
            "AggregatedResearchOutput is statically defined in .baml and should always have a type",
        )
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `title` field builder.
    pub fn property_title(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("title")
            .expect("AggregatedResearchOutput.title is statically defined in .baml and should always be present")
    }

    /// Access the `citation` field builder.
    pub fn property_citation(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("citation")
            .expect("AggregatedResearchOutput.citation is statically defined in .baml and should always be present")
    }

    /// Access the `topics` field builder.
    pub fn property_topics(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("topics")
            .expect("AggregatedResearchOutput.topics is statically defined in .baml and should always be present")
    }

    /// Access the `summary` field builder.
    pub fn property_summary(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("summary")
            .expect("AggregatedResearchOutput.summary is statically defined in .baml and should always be present")
    }

    /// Access the `key_ideas` field builder.
    pub fn property_key_ideas(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("key_ideas")
            .expect("AggregatedResearchOutput.key_ideas is statically defined in .baml and should always be present")
    }

    /// Access the `implementation_notes` field builder.
    pub fn property_implementation_notes(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("implementation_notes")
            .expect("AggregatedResearchOutput.implementation_notes is statically defined in .baml and should always be present")
    }

    /// Access the `critique` field builder.
    pub fn property_critique(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("critique")
            .expect("AggregatedResearchOutput.critique is statically defined in .baml and should always be present")
    }

    /// Access the `evidence_span_ids` field builder.
    pub fn property_evidence_span_ids(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("evidence_span_ids")
            .expect("AggregatedResearchOutput.evidence_span_ids is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `DocumentClassification` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct DocumentClassificationClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl DocumentClassificationClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type().expect(
            "DocumentClassification is statically defined in .baml and should always have a type",
        )
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `title` field builder.
    pub fn property_title(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("title")
            .expect("DocumentClassification.title is statically defined in .baml and should always be present")
    }

    /// Access the `authors` field builder.
    pub fn property_authors(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("authors")
            .expect("DocumentClassification.authors is statically defined in .baml and should always be present")
    }

    /// Access the `source_type` field builder.
    pub fn property_source_type(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("source_type")
            .expect("DocumentClassification.source_type is statically defined in .baml and should always be present")
    }

    /// Access the `language` field builder.
    pub fn property_language(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("language")
            .expect("DocumentClassification.language is statically defined in .baml and should always be present")
    }

    /// Access the `topics` field builder.
    pub fn property_topics(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("topics")
            .expect("DocumentClassification.topics is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `EvidenceReferenceOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct EvidenceReferenceOutputClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl EvidenceReferenceOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type().expect(
            "EvidenceReferenceOutput is statically defined in .baml and should always have a type",
        )
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `quote` field builder.
    pub fn property_quote(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("quote")
            .expect("EvidenceReferenceOutput.quote is statically defined in .baml and should always be present")
    }

    /// Access the `location` field builder.
    pub fn property_location(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("location")
            .expect("EvidenceReferenceOutput.location is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `ResearchChunkOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ResearchChunkOutputClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl ResearchChunkOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type().expect(
            "ResearchChunkOutput is statically defined in .baml and should always have a type",
        )
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `summary` field builder.
    pub fn property_summary(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("summary")
            .expect("ResearchChunkOutput.summary is statically defined in .baml and should always be present")
    }

    /// Access the `key_ideas` field builder.
    pub fn property_key_ideas(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("key_ideas")
            .expect("ResearchChunkOutput.key_ideas is statically defined in .baml and should always be present")
    }

    /// Access the `implementation_notes` field builder.
    pub fn property_implementation_notes(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("implementation_notes")
            .expect("ResearchChunkOutput.implementation_notes is statically defined in .baml and should always be present")
    }

    /// Access the `critique_points` field builder.
    pub fn property_critique_points(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("critique_points")
            .expect("ResearchChunkOutput.critique_points is statically defined in .baml and should always be present")
    }

    /// Access the `evidence_span_ids` field builder.
    pub fn property_evidence_span_ids(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("evidence_span_ids")
            .expect("ResearchChunkOutput.evidence_span_ids is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `ResearchDraftOutput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ResearchDraftOutputClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl ResearchDraftOutputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type().expect(
            "ResearchDraftOutput is statically defined in .baml and should always have a type",
        )
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `title` field builder.
    pub fn property_title(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("title").expect(
            "ResearchDraftOutput.title is statically defined in .baml and should always be present",
        )
    }

    /// Access the `citation` field builder.
    pub fn property_citation(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("citation")
            .expect("ResearchDraftOutput.citation is statically defined in .baml and should always be present")
    }

    /// Access the `topics` field builder.
    pub fn property_topics(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("topics")
            .expect("ResearchDraftOutput.topics is statically defined in .baml and should always be present")
    }

    /// Access the `summary` field builder.
    pub fn property_summary(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("summary")
            .expect("ResearchDraftOutput.summary is statically defined in .baml and should always be present")
    }

    /// Access the `key_ideas` field builder.
    pub fn property_key_ideas(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("key_ideas")
            .expect("ResearchDraftOutput.key_ideas is statically defined in .baml and should always be present")
    }

    /// Access the `implementation_notes` field builder.
    pub fn property_implementation_notes(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("implementation_notes")
            .expect("ResearchDraftOutput.implementation_notes is statically defined in .baml and should always be present")
    }

    /// Access the `critique` field builder.
    pub fn property_critique(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("critique")
            .expect("ResearchDraftOutput.critique is statically defined in .baml and should always be present")
    }

    /// Access the `evidence` field builder.
    pub fn property_evidence(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("evidence")
            .expect("ResearchDraftOutput.evidence is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `SourceSpanInput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct SourceSpanInputClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl SourceSpanInputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner
            .as_type()
            .expect("SourceSpanInput is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `id` field builder.
    pub fn property_id(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("id").expect(
            "SourceSpanInput.id is statically defined in .baml and should always be present",
        )
    }

    /// Access the `text` field builder.
    pub fn property_text(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("text").expect(
            "SourceSpanInput.text is statically defined in .baml and should always be present",
        )
    }

    /// Access the `location` field builder.
    pub fn property_location(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("location").expect(
            "SourceSpanInput.location is statically defined in .baml and should always be present",
        )
    }
}
